# Generated by Django 3.2.15 on 2022-08-31 12:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', cloudinary.models.CloudinaryField(default='default_image', max_length=255, verbose_name='category_icon')),
            ],
        ),
    ]
