# Generated by Django 3.2.15 on 2022-08-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'family members'},
        ),
    ]
