# Generated by Django 3.2.15 on 2022-08-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220831_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'family members'},
        ),
    ]
