# Generated by Django 3.2.15 on 2022-08-28 13:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('family_member_img', cloudinary.models.CloudinaryField(default='default_image', max_length=255, verbose_name='family_member_image')),
                ('role', models.IntegerField(choices=[(0, 'Child'), (1, 'Parent')], default=0)),
                ('star_points', models.IntegerField(default='0')),
                ('ongoing_tasks', models.IntegerField(default='0')),
                ('closed_tasks', models.IntegerField(default='0')),
            ],
            options={
                'verbose_name_plural': 'family members',
            },
        ),
    ]
