# Generated by Django 3.2.15 on 2022-09-10 17:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='family_member_img',
            field=cloudinary.models.CloudinaryField(default='default_image', max_length=255, verbose_name='family_member_img'),
        ),
    ]
